version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - golang
    groups:
      gomod-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
